### ISSUE TITLE
NaN Double values are not handled, which results in an error parsing Firestore Documents

### ISSUE THREAD

**Issue by markbreuss** [invertase/dart_firebase_apis#7]
To put it simply, this document:
![image](https://github.com/invertase/dart_firebase_apis/assets/69714845/748c3217-2745-416e-845e-8d1a2cefe78c)

produces the following error in the conversion:
![image](https://github.com/invertase/dart_firebase_apis/assets/69714845/bf7d1dea-5969-417c-b17f-1a9aec8082eb)

I can reproduce and more than willing to hop on a call to test it.
Im not versed in code generation so I'd appreceate someone stepping in with a PR.

Original Issue in Firebase Admin SDK:
https://github.com/invertase/dart_firebase_admin/issues/29

See also Firestore official docs mentioning NaN values:
https://firebase.google.com/docs/firestore/manage-data/data-types

**Comment by rrousselGit** [comment]
I've moved the issue to the google repo. This is a fork of it
